
import React, { useState, useRef } from 'react';
import { RecipeResult } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

interface Props {
  result: RecipeResult;
  canGoBack: boolean;
  canGoForward: boolean;
  onReset: () => void;
  onRegenerate: () => void;
  onViewAlternative: (dishName: string) => void;
  onGoBack: () => void;
  onGoForward: () => void;
}

const ResultView: React.FC<Props> = ({ 
  result, 
  canGoBack, 
  canGoForward, 
  onReset, 
  onRegenerate, 
  onViewAlternative, 
  onGoBack, 
  onGoForward 
}) => {
  const [tab, setTab] = useState<'easy' | 'gourmet'>('easy');
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  const handleDownloadPDF = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);

    try {
      // 1. Capture the DOM element as a canvas
      const canvas = await html2canvas(contentRef.current, {
        scale: 2, // High resolution
        useCORS: true, // Handle cross-origin images
        allowTaint: true,
        backgroundColor: '#ffffff'
      });

      // 2. Convert canvas to image data
      const imgData = canvas.toDataURL('image/png');

      // 3. Create PDF with the same dimensions as the captured content (in mm)
      // Conversion factor: 1 px = 0.264583 mm
      const imgWidth = canvas.width * 0.264583;
      const imgHeight = canvas.height * 0.264583;

      const pdf = new jsPDF({
        orientation: imgWidth > imgHeight ? 'l' : 'p',
        unit: 'mm',
        format: [imgWidth, imgHeight]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`${result.dishName}_레시피.pdf`);

    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("PDF 저장 중 오류가 발생했습니다.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="animate-fadeIn space-y-8 pb-20 pt-10">
      {/* Content to be Captured */}
      <div ref={contentRef} className="bg-white p-4 rounded-[32px]">
        <div className="text-center space-y-6">
          <div className="inline-block px-4 py-1.5 bg-orange-50 text-[#ff5d01] text-xs font-black rounded-full uppercase tracking-widest">
            Recipe Completed
          </div>
          
          {result.imageUrl && (
            <div className="w-full h-64 rounded-[32px] overflow-hidden shadow-lg mb-6 border border-orange-50 relative group">
              <img 
                src={result.imageUrl} 
                alt={result.dishName} 
                className="w-full h-full object-cover"
              />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/50 to-transparent p-4">
                <span className="text-white/80 text-xs font-medium">Generated by Gemini Nano Banana</span>
              </div>
            </div>
          )}

          <h2 className="text-3xl font-black text-slate-900 leading-tight">
            {result.dishName}
          </h2>
          <div className="relative px-6">
            <p className="text-slate-500 italic text-lg font-medium leading-relaxed">
              "{result.comment}"
            </p>
          </div>
        </div>

        {/* 재료 목록 섹션 */}
        {result.ingredientsList && (
          <div className="bg-white rounded-[24px] p-6 shadow-sm border border-slate-50 mt-6">
            <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
              <span className="text-xl">🛒</span> 필요 재료
            </h3>
            <div 
              className="prose prose-sm prose-slate max-w-none text-slate-600 font-medium ingredients-list"
              dangerouslySetInnerHTML={{ __html: result.ingredientsList }}
            />
          </div>
        )}

        {/* Tab Selection (Visual only, Logic below) */}
        <div className="bg-[#F2F4F6] p-1.5 rounded-2xl flex mt-8 mb-6 border border-slate-100">
          <div
            className={`flex-1 py-3 text-center text-sm font-black rounded-xl ${
              tab === 'easy' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-400'
            }`}
          >
            ⚡ 간편 레시피
          </div>
          <div
            className={`flex-1 py-3 text-center text-sm font-black rounded-xl ${
              tab === 'gourmet' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-400'
            }`}
          >
            ✨ 꿀팁 & 킥
          </div>
        </div>

        <div className="bg-white rounded-[32px] p-8 shadow-sm border border-slate-50">
          <h3 className="text-xl font-black text-slate-900 mb-8 brand-orange-text">
            {tab === 'easy' ? '간편 조리법' : '셰프의 특별 레시피'}
          </h3>
          <div 
            className="recipe-content prose prose-slate max-w-none text-slate-800 font-medium"
            dangerouslySetInnerHTML={{ __html: tab === 'easy' ? result.easyRecipe : result.gourmetRecipe }}
          />
        </div>

        <div className="space-y-4 mt-8">
          <h3 className="text-lg font-black text-slate-900">다른 추천 메뉴</h3>
          <div className="grid gap-3">
            {result.similarRecipes.map((recipe, idx) => (
              <div key={idx} className="bg-orange-50/30 p-6 rounded-3xl border border-orange-100 flex flex-col gap-3">
                <div>
                  <h4 className="text-lg font-black text-orange-900">{recipe.title}</h4>
                  <p className="text-sm text-orange-700/70 font-medium leading-relaxed">{recipe.reason}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {result.referenceLinks && result.referenceLinks.length > 0 && (
          <div className="space-y-4 pt-8">
            <h3 className="text-lg font-black text-slate-900">참고 링크</h3>
            <div className="flex flex-col gap-2">
              {result.referenceLinks.map((link, idx) => (
                <div 
                  key={idx} 
                  className="w-full p-4 bg-slate-50 border border-slate-100 text-slate-600 text-sm font-bold rounded-2xl flex justify-between items-center"
                >
                  <span>🔗 {link.title}</span>
                </div>
              ))}
            </div>
          </div>
        )}
        <div className="text-center mt-8 text-slate-300 text-xs font-mono">
           Powered by 웅아! 오늘 뭐 해먹지? AI Chef
        </div>
      </div>
      {/* End of Capture Ref */}


      {/* Control Buttons (Not Captured) */}
      <div className="bg-[#F2F4F6] rounded-2xl p-1.5 flex mb-4 sticky top-4 z-30 shadow-md mx-4">
        <button
          onClick={() => setTab('easy')}
          className={`flex-1 py-3 text-sm font-black rounded-xl transition-all ${
            tab === 'easy' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-500'
          }`}
        >
          ⚡ 간편
        </button>
        <button
          onClick={() => setTab('gourmet')}
          className={`flex-1 py-3 text-sm font-black rounded-xl transition-all ${
            tab === 'gourmet' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-500'
          }`}
        >
          ✨ 꿀팁
        </button>
      </div>

      <div className="flex flex-col gap-3 px-4">
        <div className="flex gap-2 w-full">
          {canGoBack && (
            <button
              onClick={onGoBack}
              className="flex-1 py-5 bg-orange-50 text-[#ff5d01] font-bold text-lg rounded-[24px] border border-orange-100 active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              ⬅️ 이전
            </button>
          )}
          {canGoForward && (
            <button
              onClick={onGoForward}
              className="flex-1 py-5 bg-orange-50 text-[#ff5d01] font-bold text-lg rounded-[24px] border border-orange-100 active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              다음 ➡️
            </button>
          )}
        </div>
        
        <button
          onClick={handleDownloadPDF}
          disabled={isDownloading}
          className="w-full py-5 bg-slate-800 text-white font-bold text-lg rounded-[24px] shadow-lg shadow-slate-200 active:scale-95 transition-all flex items-center justify-center gap-2"
        >
          {isDownloading ? (
            <>⏳ 저장 중...</>
          ) : (
            <>📄 레시피 PDF로 저장</>
          )}
        </button>

        <button
          onClick={onRegenerate}
          className="w-full py-6 bg-white border-2 border-[#ff5d01] text-[#ff5d01] font-bold text-xl rounded-[24px] shadow-sm active:scale-95 transition-all"
        >
          🔄 다른 레시피 추천받기
        </button>
        <button
          onClick={onReset}
          className="w-full py-6 bg-[#ff5d01] text-white font-bold text-xl rounded-[24px] shadow-xl shadow-orange-200 active:scale-95 transition-all"
        >
          🏠 처음부터 다시하기
        </button>
      </div>

      <div className="px-4 pb-4">
        <h3 className="text-lg font-black text-slate-900 mb-2">링크 바로가기</h3>
         <div className="flex flex-col gap-2">
            {result.referenceLinks && result.referenceLinks.map((link, idx) => (
              <a 
                key={idx} 
                href={link.url} 
                target="_blank" 
                rel="noreferrer"
                className="w-full p-4 bg-white border border-slate-200 text-slate-600 text-sm font-bold rounded-2xl hover:bg-slate-50 transition-all flex justify-between items-center"
              >
                <span>🔗 {link.title}</span>
                <span className="text-slate-300">➔</span>
              </a>
            ))}
          </div>
      </div>

      <style>{`
        .recipe-content ol { list-style: none; counter-reset: r-step; padding: 0; display: flex; flex-direction: column; gap: 1.5rem; }
        .recipe-content ol li { counter-increment: r-step; position: relative; padding-left: 3.5rem; font-size: 1.1rem; line-height: 1.6; }
        .recipe-content ol li::before {
          content: counter(r-step);
          position: absolute; left: 0; top: 0;
          width: 2.2rem; height: 2.2rem;
          background: #FFF3ED; color: #ff5d01;
          display: flex; align-items: center; justify-content: center;
          border-radius: 12px; font-weight: 900; font-size: 0.9rem;
        }
        .ingredients-list ul { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: 1fr; gap: 0.5rem; }
        .ingredients-list li { display: flex; align-items: center; gap: 0.5rem; background: #f8fafc; padding: 0.8rem 1rem; border-radius: 8px; font-size: 0.95rem; }
        .ingredients-list li::before { content: '•'; color: #ff5d01; font-weight: bold; }
      `}</style>
    </div>
  );
};

export default ResultView;
