
import React, { useState, useRef } from 'react';
import { RecipeResult } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { incrementDownloadCount, updateRating, updateVote } from '../services/supabase.ts';

interface Props {
  result: RecipeResult;
  canGoBack: boolean;
  canGoForward: boolean;
  onReset: () => void;
  onRegenerate: () => void;
  onViewAlternative: (dishName: string) => void;
  onGoBack: () => void;
  onGoForward: () => void;
}

const ResultView: React.FC<Props> = ({ 
  result, 
  canGoBack, 
  canGoForward, 
  onReset, 
  onRegenerate, 
  onViewAlternative, 
  onGoBack, 
  onGoForward 
}) => {
  const [tab, setTab] = useState<'easy' | 'gourmet'>('easy');
  const [isDownloading, setIsDownloading] = useState(false);
  const [rating, setRating] = useState<number>(0);
  const [feedback, setFeedback] = useState<'success' | 'fail' | null>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  // DB에 저장된 ID가 없으면 로컬 전용으로 간주
  const isDBSaved = !!result.id;

  const handleDownloadPDF = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);

    try {
      // 실제 DB 다운로드 카운트 증가
      if (result.id) {
        await incrementDownloadCount(result.id);
        console.log(`[Analytics] '${result.dishName}' (ID: ${result.id}) PDF Download Recorded.`);
      }

      const canvas = await html2canvas(contentRef.current, {
        scale: 2, 
        useCORS: true, 
        allowTaint: true,
        backgroundColor: '#ffffff'
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = canvas.width * 0.264583;
      const imgHeight = canvas.height * 0.264583;

      const pdf = new jsPDF({
        orientation: imgWidth > imgHeight ? 'l' : 'p',
        unit: 'mm',
        format: [imgWidth, imgHeight]
      });

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);
      pdf.save(`${result.dishName}_레시피.pdf`);

    } catch (error) {
      console.error("PDF generation failed:", error);
      alert("PDF 저장 중 오류가 발생했습니다.");
    } finally {
      setIsDownloading(false);
    }
  };

  const handleRating = async (score: number) => {
    setRating(score);
    if (result.id) {
      await updateRating(result.id, score);
      console.log(`[Analytics] Rated ${score} stars for ID: ${result.id}`);
    }
  };

  const handleFeedback = async (type: 'success' | 'fail') => {
    if (feedback) return; // 이미 투표함
    setFeedback(type);
    if (result.id) {
      await updateVote(result.id, type);
      console.log(`[Analytics] Voted ${type} for ID: ${result.id}`);
    }
  };

  return (
    <div className="animate-fadeIn space-y-8 pb-10 pt-10">
      {/* Content to be Captured */}
      <div ref={contentRef} className="bg-white p-4 rounded-[32px]">
        <div className="text-center space-y-6">
          <div className="flex justify-center gap-2 items-center">
            <div className="inline-block px-4 py-1.5 bg-orange-50 text-[#ff5d01] text-xs font-black rounded-full uppercase tracking-widest">
              Recipe Completed
            </div>
            {isDBSaved ? (
              <div className="inline-block px-3 py-1.5 bg-slate-100 text-slate-500 text-xs font-bold rounded-full flex items-center gap-1">
                <span>☁️</span> 서버 저장됨
              </div>
            ) : (
               <div className="inline-block px-3 py-1.5 bg-slate-100 text-slate-400 text-xs font-bold rounded-full flex items-center gap-1">
                <span>⚠️</span> 로컬 모드
              </div>
            )}
          </div>
          
          {result.imageUrl && (
            <div className="w-full h-64 rounded-[32px] overflow-hidden shadow-lg mb-6 border border-orange-50 relative group">
              <img 
                src={result.imageUrl} 
                alt={result.dishName} 
                className="w-full h-full object-cover"
                crossOrigin="anonymous" // CORS issue for html2canvas
              />
              <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/50 to-transparent p-4">
                <span className="text-white/80 text-xs font-medium">Generated by Gemini Nano Banana</span>
              </div>
            </div>
          )}

          <h2 className="text-3xl font-black text-slate-900 leading-tight">
            {result.dishName}
          </h2>
          <div className="relative px-6">
            <p className="text-slate-500 italic text-lg font-medium leading-relaxed">
              "{result.comment}"
            </p>
          </div>
        </div>

        {/* 재료 목록 섹션 */}
        {result.ingredientsList && (
          <div className="bg-white rounded-[24px] p-6 shadow-sm border border-slate-50 mt-6">
            <h3 className="text-lg font-black text-slate-900 mb-4 flex items-center gap-2">
              <span className="text-xl">🛒</span> 필요 재료
            </h3>
            <div 
              className="prose prose-sm prose-slate max-w-none text-slate-600 font-medium ingredients-list"
              dangerouslySetInnerHTML={{ __html: result.ingredientsList }}
            />
          </div>
        )}

        {/* Tab Selection (Functional & Capturable) */}
        {/* data-html2canvas-ignore="true"를 추가하면 PDF 저장 시 이 버튼 영역은 제외됩니다. */}
        <div 
          className="bg-[#F2F4F6] p-1.5 rounded-2xl flex mt-8 mb-6 border border-slate-100"
          data-html2canvas-ignore="true"
        >
          <button
            onClick={() => setTab('easy')}
            className={`flex-1 py-3 text-center text-sm font-black rounded-xl transition-all ${
              tab === 'easy' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-400'
            }`}
          >
            ⚡ 간편 레시피
          </button>
          <button
            onClick={() => setTab('gourmet')}
            className={`flex-1 py-3 text-center text-sm font-black rounded-xl transition-all ${
              tab === 'gourmet' ? 'bg-white text-[#ff5d01] shadow-sm' : 'text-slate-400'
            }`}
          >
            ✨ 꿀팁 & 킥
          </button>
        </div>

        <div className="bg-white rounded-[32px] p-8 shadow-sm border border-slate-50">
          <h3 className="text-xl font-black text-slate-900 mb-8 brand-orange-text">
            {tab === 'easy' ? '간편 조리법' : '셰프의 특별 레시피'}
          </h3>
          <div 
            className="recipe-content prose prose-slate max-w-none text-slate-800 font-medium"
            dangerouslySetInnerHTML={{ __html: tab === 'easy' ? result.easyRecipe : result.gourmetRecipe }}
          />
        </div>

        <div className="space-y-4 mt-8">
          <h3 className="text-lg font-black text-slate-900">다른 추천 메뉴</h3>
          <div className="grid gap-3">
            {result.similarRecipes.map((recipe, idx) => (
              <button 
                key={idx} 
                onClick={() => onViewAlternative(recipe.title)}
                className="w-full text-left bg-orange-50/30 p-6 rounded-3xl border border-orange-100 flex flex-col gap-3 hover:bg-orange-50 active:scale-95 transition-all group"
              >
                <div>
                  <h4 className="text-lg font-black text-orange-900 flex items-center justify-between">
                    {recipe.title}
                    <span className="text-xs bg-white/50 text-[#ff5d01] px-2 py-1 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity">
                      레시피 보기 ➔
                    </span>
                  </h4>
                  <p className="text-sm text-orange-700/70 font-medium leading-relaxed mt-1">{recipe.reason}</p>
                </div>
              </button>
            ))}
          </div>
        </div>

        {result.referenceLinks && result.referenceLinks.length > 0 && (
          <div className="space-y-4 pt-8">
            <h3 className="text-lg font-black text-slate-900">참고 링크</h3>
            <div className="flex flex-col gap-2">
              {result.referenceLinks.map((link, idx) => (
                <a 
                  key={idx} 
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="w-full p-4 bg-slate-50 border border-slate-100 text-slate-600 text-sm font-bold rounded-2xl flex justify-between items-center hover:bg-slate-100 transition-colors"
                >
                  <span>🔗 {link.title}</span>
                  <span className="text-slate-400">↗</span>
                </a>
              ))}
            </div>
          </div>
        )}
        
        {/* PDF Branding Footer */}
        <div className="text-center mt-8 text-slate-300 text-xs font-mono">
           Powered by 웅이 연구소
        </div>
      </div>
      {/* End of Capture Ref */}

      
      {/* Community Feedback Section */}
      <div className="mx-4 mb-6 bg-white rounded-[24px] p-6 shadow-sm border border-slate-100 space-y-4">
        <div className="text-center space-y-1">
          <h3 className="text-lg font-black text-slate-900">이 레시피 어떠셨나요?</h3>
          <p className="text-xs text-slate-400">
            {isDBSaved ? '평가를 남겨주시면 명예의 전당에 반영됩니다!' : '서버와 연결되지 않아 기록되지 않아요.'}
          </p>
        </div>
        
        {/* Star Rating */}
        <div className="flex justify-center gap-2">
          {[1, 2, 3, 4, 5].map((star) => (
            <button
              key={star}
              onClick={() => handleRating(star)}
              disabled={!isDBSaved}
              className={`text-3xl transition-transform active:scale-125 ${star <= rating ? 'grayscale-0' : 'grayscale opacity-30'} ${!isDBSaved && 'cursor-not-allowed opacity-20'}`}
            >
              ⭐
            </button>
          ))}
        </div>

        {/* Success/Fail Vote */}
        <div className="flex gap-2">
          <button
            onClick={() => handleFeedback('success')}
            disabled={!isDBSaved || feedback !== null}
            className={`flex-1 py-3 rounded-xl border-2 font-bold text-sm transition-all ${
              feedback === 'success' 
              ? 'border-green-500 bg-green-50 text-green-600' 
              : 'border-slate-100 text-slate-400 hover:border-green-200 hover:text-green-500'
            } ${!isDBSaved && 'opacity-50 cursor-not-allowed'}`}
          >
            😋 성공했어요!
          </button>
          <button
            onClick={() => handleFeedback('fail')}
            disabled={!isDBSaved || feedback !== null}
            className={`flex-1 py-3 rounded-xl border-2 font-bold text-sm transition-all ${
              feedback === 'fail' 
              ? 'border-red-500 bg-red-50 text-red-600' 
              : 'border-slate-100 text-slate-400 hover:border-red-200 hover:text-red-500'
            } ${!isDBSaved && 'opacity-50 cursor-not-allowed'}`}
          >
            🥲 망했어요..
          </button>
        </div>
      </div>

      <div className="flex flex-col gap-3 px-4">
        <div className="flex gap-2 w-full">
          {canGoBack && (
            <button
              onClick={onGoBack}
              className="flex-1 py-5 bg-orange-50 text-[#ff5d01] font-bold text-lg rounded-[24px] border border-orange-100 active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              ⬅️ 이전
            </button>
          )}
          {canGoForward && (
            <button
              onClick={onGoForward}
              className="flex-1 py-5 bg-orange-50 text-[#ff5d01] font-bold text-lg rounded-[24px] border border-orange-100 active:scale-95 transition-all flex items-center justify-center gap-2"
            >
              다음 ➡️
            </button>
          )}
        </div>
        
        <button
          onClick={handleDownloadPDF}
          disabled={isDownloading}
          className="w-full py-5 bg-slate-800 text-white font-bold text-lg rounded-[24px] shadow-lg shadow-slate-200 active:scale-95 transition-all flex items-center justify-center gap-2"
        >
          {isDownloading ? (
            <>⏳ 저장 및 집계 중...</>
          ) : (
            <>📄 레시피 PDF로 저장</>
          )}
        </button>

        <button
          onClick={onRegenerate}
          className="w-full py-6 bg-white border-2 border-[#ff5d01] text-[#ff5d01] font-bold text-xl rounded-[24px] shadow-sm active:scale-95 transition-all"
        >
          🔄 다른 레시피 추천받기
        </button>
        <button
          onClick={onReset}
          className="w-full py-6 bg-[#ff5d01] text-white font-bold text-xl rounded-[24px] shadow-xl shadow-orange-200 active:scale-95 transition-all"
        >
          🏠 처음부터 다시하기
        </button>
      </div>

      {/* Screen Bottom Footer */}
      <div className="text-center py-6 text-slate-300 text-xs font-mono">
         Powered by 퓨전요리연구소
      </div>

      <style>{`
        .recipe-content ol { list-style: none; counter-reset: r-step; padding: 0; display: flex; flex-direction: column; gap: 1.5rem; }
        .recipe-content ol li { counter-increment: r-step; position: relative; padding-left: 3.5rem; font-size: 1.1rem; line-height: 1.6; }
        .recipe-content ol li::before {
          content: counter(r-step);
          position: absolute; left: 0; top: 0;
          width: 2.2rem; height: 2.2rem;
          background: #FFF3ED; color: #ff5d01;
          display: flex; align-items: center; justify-content: center;
          border-radius: 12px; font-weight: 900; font-size: 0.9rem;
        }
        .ingredients-list ul { list-style: none; padding: 0; margin: 0; display: grid; grid-template-columns: 1fr; gap: 0.5rem; }
        .ingredients-list li { display: flex; align-items: center; gap: 0.5rem; background: #f8fafc; padding: 0.8rem 1rem; border-radius: 8px; font-size: 0.95rem; }
        .ingredients-list li::before { content: '•'; color: #ff5d01; font-weight: bold; }
      `}</style>
    </div>
  );
};

export default ResultView;
